################### MQTT ###################
mqtt:
  enabled: true
  host: 192.168.28.110
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: Admin
  password: 197ak0801
  stats_interval: 60

################### GO2RTC ###################
go2rtc:
  streams:
    reolink:
      - rtsp://frigate:reoFrigatelink@192.168.28.99:554/h264Preview_01_sub
      - ffmpeg:rtsp://frigate:reoFrigatelink@192.168.28.99:554/h264Preview_01_sub#audio=pc#audio=volume

  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30db"

################### CAMERAS ###################
cameras:
  frontdoor_camera:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://frigate:reoFrigatelink@192.168.28.99:554/h264Preview_01_sub # <----- The stream you want to use for detection
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-copy

################### GLOBAL CAMERA SETTINGS ###################

objects:
  track: 
    - person
  filters:
    person:
      treshold: 0.7

detect:
  enabled: false # <---- disable detection until you have a working camera feed
  width: 800
  height: 480

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 14

record:
  enabled: true
  #retain_days: 0
  events:
    retain:
      default: 7
