- platform: ping
  host: 192.168.10.1
  name: router
  count: 5
  scan_interval: 5
- platform: ping
  host: 79.160.116.6
  name: isp
  count: 5
  scan_interval: 5
- platform: ping
  host: 17.253.144.10
  name: apple
  count: 5
  scan_interval: 5
  