
# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  # Load packages
  packages: !include_dir_named integrations

#######################################################
# Packages that MUST stay in configuration.yaml file
#######################################################

logbook:

history:

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js

    # Extra logging options
logger:
  default: warning
  logs:
    custom_components.powercalc: debug

# Shell commands
shell_command:
  push_upload_git: /bin/bash push_upload_git.sh




#######################################################
# Include files
#
# These sections can be moved into the new split configuration methode
#
#######################################################
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
camera: !include cameras.yaml
switch: !include switch.yaml
counter: !include counters.yaml
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
#powercalc: !include powercalc.yaml


battery_notes: 
  enable_autodiscovery: true
  show_all_devices: false
  enable_replaced: true
  default_battery_low_threshold: 10
  battery_increase_threshold: 25
  hide_battery: false
  round_battery: false


