#
# System Monitor
# - https://www.home-assistant.io/integrations/systemmonitor/
#
- platform: systemmonitor
  resources:
    - type: processor_use      
    - type: disk_use_percent
      arg: /config
    - type: memory_free
    - type: load_1m
    - type: load_5m
    - type: load_15m

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'
    
#
# Estimated outside illuminance
# - https://community.home-assistant.io/t/outdoor-illuminance-estimated-from-weather-conditions/52756
#
- platform: illuminance
  name: Estimated Illuminance
  entity_id: weather.home

#
# Sensors in the Average platform
#
- platform: average
  name: 'Panel oven BR - avg Power'
  unique_id: fdba4864-5fcd-40bc-b56e-673a86e59327
  duration:
    hours: 3
  entities: 
    - sensor.panel_oven_br_power

- platform: average
  name: 'Panel oven FD - avg Power'
  unique_id: 2235c274-78bb-4825-a626-82ad817fd72b
  duration:
    hours: 3
  entities: 
    - sensor.panel_oven_fd_power

- platform: average
  name: 'Refrigerator - avg Power'
  unique_id: b4e4281b-42f9-4356-b68c-fa050f9cc15c
  duration:
    hours: 3
  entities: 
    - sensor.refrigerator_power

- platform: average
  name: 'Freezer - avg Power'
  unique_id: 63529b8e-9b3f-4ded-b840-9047023dd83c
  duration:
    hours: 3
  entities: 
    - sensor.freezer_power

- platform: average
  name: 'Varmepumpe - avg Power'
  unique_id: a7681680-2920-432f-a6a0-4343439196b6
  duration:
    minutes: 5
  entities: 
    - sensor.varmepumpe_power

- platform: average
  name: 'Washing machine - avg Power'
  unique_id: 2bc5518a-e949-4678-8a4b-ee64bb81f20c
  duration:
    minutes: 15
  entities:
    sensor.washing_machine_power_module_power

- platform: average
  name: 'Tumble dryer - avg Power'
  unique_id: ecf31280-eb31-4ba6-955f-34da8c6d0ec4
  duration:
    minutes: 15
  entities:
    sensor.tumble_dryer_power_module_power

#
# Sensors in the REST Platform
#
- platform: rest
  scan_interval: 7200
  name: ice warning
  unique_id: b68ce24a-4150-4185-89bb-67ee95d2256d
  resource: https://api.eiswarnung.de?key=c000f6617d7cff3826cbd91533608be6&lat=59.97761&lng=11.24198
  json_attributes:
    - success
    - message
    - callsLeft
    - callsDailyLimit
    - callsResetInSeconds
    - result
  value_template: "{{ value_json.result.forecastId }}"
