##################################################
# Diesel logbook
# - Total liters diesel filled this week
# - Rest liters diesel to fill this week
# - Overage / Underage liters diesel from last week
#
##################################################
# Entities used by Diesel Logbook
# - input_text.keypad_input
# - input_number.diesel_target
# - input_number.diesel_rest
# - input_number.diesel[1-7]
#
##################################################
# Sensors created by Diesel Logbook
# - sensor.keypad_input
# - sensor.diesel_target
# - sensor.diesel_rest
# - sensor.diesel_day
# - sensor.diesel_week
# - sensor.diesel_todo
# - sensor.diesel_[1-7]
#
##################################################
sensor:

  - name: keypad_input
    unique_id: 2bf5849a-a10d-4c21-9e74-29e84e4f1f5b
    state: >
      {% set kim = states('input_text.keypad_input') | int %}
      {{ kim }}

  - name: diesel_target
    unique_id: c6c16882-562e-4e54-a0e9-94127cfe3128
    icon: mdi:fuel
    state: >
      {% set di =  states('input_number.diesel_target') | int %}
      {{ di }}

  - name: diesel_rest
    unique_id: ddf25a20-3549-4cd8-83a6-e1cb1590e4b6
    icon: mdi:fuel
    state: >
      {% set di =  states('input_number.diesel_rest') | int %}
      {{ di }}

  - name: diesel_day
    unique_id: 56aa7004-d50d-41cf-812f-5e57fcf1d7f7
    icon: mdi:fuel
    state: >
      {% set di =  states('input_number.diesel_input') | int %}
      {{ di }}

  - name: diesel_week
    unique_id: 24f9890a-e1d8-4ea9-b044-770eb79557aa
    icon: mdi:fuel
    state: >
      {% set d1 =  states('input_number.diesel_1') | int %}
      {% set d2 =  states('input_number.diesel_2') | int %}
      {% set d3 =  states('input_number.diesel_3') | int %}
      {% set d4 =  states('input_number.diesel_4') | int %}
      {% set d5 =  states('input_number.diesel_5') | int %}
      {% set d6 =  states('input_number.diesel_6') | int %}
      {% set d7 =  states('input_number.diesel_7') | int %}
      {% set dw = (d1 + d2 + d3 + d4 + d5 + d6 + d7) | int %}
      {{ dw }}

  - name: diesel_todo
    unique_id: c527fa64-5133-4cdb-8f40-a5e64d3ad4f0
    icon: mdi:fuel
    state: >
      {% set dt =  states('sensor.diesel_target') | int %}
      {% set dw =  states('sensor.diesel_week') | int %}
      {% set dr =  states('sensor.diesel_rest') | int %}
      {% set dtg = (dt - dw + dr) | int %}
      {{ dtg }}

  - name: diesel_1
    unique_id: a1d58d75-6103-433b-83f4-39b2b58fbb60
    icon: mdi:fuel
    state: >
      {% set di =  states('input_number.diesel_1') | int %}
      {{ di }}

  - name: diesel_2
    unique_id: 74d2bec4-c625-4128-ab06-ece0a55be2ee
    icon: mdi:fuel
    state: >
      {% set di =  states('input_number.diesel_2') | int %}
      {{ di }}

  - name: diesel_3
    unique_id: 7751a39c-da3b-4525-afe0-0b1441892e3f
    icon: mdi:fuel
    state: >
      {% set di =  states('input_number.diesel_3') | int %}
      {{ di }}

  - name: diesel_4
    unique_id: a80bb6d0-dc58-47a1-8eff-b1aab46e2ddf
    icon: mdi:fuel
    state: >
      {% set di =  states('input_number.diesel_4') | int %}
      {{ di }}

  - name: diesel_5
    unique_id: 9fb01911-d113-44d3-857b-4d9c6e04a743
    icon: mdi:fuel
    state: >
      {% set di =  states('input_number.diesel_5') | int %}
      {{ di }}
