#########################
# Enumerate ESPHome devices
#########################

sensor:
  - name: "esphome_offline_devices"
    unique_id: bdd55f79-96a3-49df-bff7-2cf396d704cb
    icon: mdi:cpu-32-bit
    state: >-
      {% set result = namespace(sensors=[]) %}
      {% for state in states.sensor | rejectattr('attributes.device_class', 'undefined') | selectattr('attributes.title', '==', 'ESPHome') %}
          {% if 'last_seen' in state.entity_id and (states(state.entity_id) == 'unavailable' or ((as_timestamp(now()) - as_timestamp(states(state.entity_id))) > ((24 | int) * 60 * 60))) %}
              {% set result.sensors = result.sensors + [state.name | regex_replace(find=' last seen', replace='') ~ ' (' ~ relative_time(strptime(states(state.entity_id), '%Y-%m-%dT%H:%M:%S%z', 'unavailable')) ~ ')'] %}
          {% endif %}
      {% endfor %}
      {{ result.sensors | join('\n') | truncate(254, True) }}

#  - name: "esphome_updatable_devices"
#    unique_id: 15195a5a-9fd2-40c3-80a9-4ca313e259bd
#    icon: mdi:cpu-32-bit
#    state: >-
#      {% set result = namespace(sensors=[]) %}
#      {% for state in states.sensor | rejectattr('attributes.device_class', 'undefined') | selectattr('attributes.title', '==', 'ESPHome') %}
#          {% if  (states(state.entity_id) == 'on'}
#              {% set result.sensors = result.sensors + [state.name ]  ~ ' (' %}
#          {% endif %}
#      {% endfor %}
#      {{ result.sensors | join('\n') | truncate(254, True) }}