################################################################################
#
# Templates used in HA
#
################################################################################

binary_sensor:
  - name: varmepumpe_on
    unique_id: 76258df1-0906-4fa3-a228-3766e4dc072a
    delay_off:
      minutes: 0
    state: >
      {{ states('sensor.varmepumpe_power')|float > 5 }}

sensor:
  #########################
  #
  # Dynamic Energy Prices tracking
  # - Nordpool region: Oslo
  #
  #########################
  - name: nordpool_energyprices
    unique_id: b59f3231-2982-43c3-ad9d-9bed780dd131
    icon: mdi:currency-sign
    unit_of_measurement: "NOK"
    state: >
      {{ states('sensor.nordpool_kwh_oslo_nok_3_10_025') | float(0) + states('input_number.nordpool_additional_costs') | float(0) }}
    attributes:
      times: >
        {% set ns = namespace(times=[]) -%}
        {%- set today = state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','raw_today') -%}
        {%- for hours in today -%}
          {%- set ns.times = ns.times + [as_local((hours.start)).strftime("%Y-%m-%d %H:%M:%S")] -%} 
        {%- endfor -%}
        {%- set tomorrow = state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','raw_tomorrow') -%}
        {%- for hours in tomorrow -%}
          {%- set ns.times = ns.times + [as_local((hours.start)).strftime("%Y-%m-%d %H:%M:%S")] -%} 
        {%- endfor -%}
        {{ ns.times }}
      prices: >
        {% set ns = namespace(prices=[]) -%}
        {%- set today = state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','raw_today') -%}
        {%- for hours in today -%}
          {%- set ns.prices = ns.prices + [hours.value + states('input_number.nordpool_additional_costs') | float(0)] -%} 
        {%- endfor -%}
        {%- set tomorrow = state_attr('sensor.nordpool_kwh_oslo_nok_3_10_025','raw_tomorrow') -%}
        {%- for hours in tomorrow -%}
          {%- if hours.value -%}
            {%- set ns.prices = ns.prices + [hours.value + states('input_number.nordpool_additional_costs') | float(0)] -%} 
          {%- endif -%}
        {%- endfor -%}
        {{ ns.prices }}

  #########################
  #
  # Debug helper template for Aqara Cube
  # - use in combination with Zigbee2MQTT - Xiaomi Cube Controler blueprint
  # - (https://community.home-assistant.io/t/zigbee2mqtt-xiaomi-cube-controller/393203)
  #
  #########################

  - name: sun.azimuth
    unique_id: 72d4a978-23df-4e2c-8a13-6aa9e7a44cba
    icon: mdi:sun-angle
    state: >
      {{ state_attr("sun.sun", "azimuth") }}

  - name: sun.elevation
    unique_id: 2d2bb2e6-93ea-4ad8-b576-f79da921419f
    icon: mdi:sun-angle
    state: >
      {{ state_attr("sun.sun", "elevation") }}
