#####
# Weater forecast new style
#
# This template pulls the weather forecast on a hourly basis
#
# https://www.home-assistant.io/integrations/template#trigger-based-handling-of-service-response-data
#####

trigger:
  - platform: time_pattern
    hours: /1
  - platform: state
    entity_id:
      - input_button.update_weather_forecast
    to: null
action:
  - service: weather.get_forecasts
    target:
      entity_id: weather.openweathermap
    data:
      type: hourly
    response_variable: my_forecast
sensor:
  - name: OpenWeather Forecast Hourly
    unique_id: 56be435a-d75c-47eb-a566-67ae041e529e
    state: "{{ now().isoformat() }}"
    attributes:
      forecast: "{{ my_forecast['weather.openweathermap'].forecast }}" 