#########################
# Enumerate Off-Line Z2MQTT devices
#########################

sensor:
  - name: "z2m_offline_devices"
    unique_id: ebd9c70b-280d-48d1-8727-a388ed4b9c54
    icon: mdi:zigbee
    state: >-
      {% set result = namespace(sensors=[]) %}
      {% for state in states.sensor | rejectattr('attributes.device_class', 'undefined') | selectattr('attributes.device_class', '==', 'timestamp') %}
          {% if 'last_seen' in state.entity_id and (states(state.entity_id) == 'unavailable' or ((as_timestamp(now()) - as_timestamp(states(state.entity_id))) > ((24 | int) * 60 * 60))) %}
              {% set result.sensors = result.sensors + [state.name | regex_replace(find=' last seen', replace='') ~ ' (' ~ relative_time(strptime(states(state.entity_id), '%Y-%m-%dT%H:%M:%S%z', 'unavailable')) ~ ')'] %}
          {% endif %}
      {% endfor %}
      {{ result.sensors | join('\n') | truncate(254, True) }}