#########################
# Enumerate Off-Line Z2MQTT devices
#########################

sensor:
  - name: "z2m_offline_devices"
    unique_id: 8d19ef4e-eabd-4028-8ff4-a4128cf0b17f
    icon: mdi:zigbee
    state: >-
      {% set result=namespace(offline_devices=[]) %} 
          {% set integrations=['mqtt', 'zwave_js', 'zha'] %}
          {% for integration in integrations %}
            {% for device in integration_entities(integration) | map('device_id') | sort | unique | list %}
              {% for entity in device_entities(device) %}
                {% if entity.startswith(('switch','sensor','binary_sensor')) and "unavailable" in expand(entity)|string  %}
                  {# add error checking, in case name_by_user==None #}
                  {% set device_name=iif(device_attr(device,"name_by_user"), device_attr(device,"name_by_user"), "ERROR", device_attr(device,"name")) %}
                  {% set result.offline_devices= result.offline_devices + [device_name] %}
                {% endif %}
              {% endfor %}
            {% endfor %}
          {% endfor %}
      {{ result.offline_devices |sort|unique| join('\n') | truncate(254, True) }}    

  # {{"Offline Devices:\n --"}} {{result.offline_devices|sort|unique|join('\n -- ')}}